# Generated by Django 4.1.4 on 2022-12-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extendeduser",
            name="username",
        ),
    ]
