[tool.black]
# We uses Black largely un-tweaked.
line-length = 88                    # keep defaults → plays nicely with many editors
target-version = ["py311", "py312"] # newest LTS runtimes in AWS Lambda
skip-string-normalization = true    # “don’t touch my quotes” policy

[tool.ruff]
line-length = 88         # keep in sync with Black
target-version = "py311" # Ruff supports only a single value

# We favours Ruff’s “flake8-like” baseline plus isort & a few extras.
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "W",   # pycodestyle warnings
  "I",   # isort import ordering
  "C90", # mccabe (complexity)
  "B",   # bugbear
  "RUF", # Ruff-specific modernisations
]

# Rules Black already guarantees → ignore to avoid duplicate noise
ignore = [
  "E501", # line length
  "E203", # whitespace before ':'
]

# Any auto-fixable offences are patched in place:
fix = true

# Extra categorisation for clearer CI output
[tool.ruff.per-file-ignores]
"tests/**/*" = [
  "S101",
  "B008",
] # allow asserts & non-abstract dataclasses in tests
"scripts/**/*" = ["E402"] # allow imports after side-effects in CLI helpers

[tool.isort]
profile = "black"
line_length = 88
known_first_party = []
known_third_party = []
