# Generated by Django 5.2 on 2025-10-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='salons',
            field=models.ManyToManyField(related_name='customers', to='salon.salon'),
        ),
    ]
