# Generated by Django 5.2 on 2025-12-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='reminder_time_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
