# Generated by Django 5.2 on 2025-10-03 15:50

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('appointment_time', models.DateTimeField()),
                ('comment', models.TextField(blank=True, default='')),
                ('column_id', models.IntegerField(default=1)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                (
                    'task_id',
                    models.CharField(blank=True, editable=False, max_length=50),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
