# Generated by Django 5.2 on 2025-10-03 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='customer.customer'
            ),
        ),
    ]
