# Generated by Django 5.0.1 on 2024-03-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_appointment_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
