# Generated by Django 5.2 on 2025-08-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='column_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
