# Generated by Django 5.2 on 2025-08-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_column_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='column_id',
            field=models.IntegerField(default=1),
        ),
    ]
