# Generated by Django 4.1.4 on 2023-06-06 21:06

from django.db import migrations, models

import address.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_alter_address_options_address_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=8,
                validators=[address.helpers.validate_uk_postcode],
            ),
        ),
    ]
