# Generated by Django 4.1.4 on 2023-06-01 21:23

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
        ("salon", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendeduser",
            name="addresses",
            field=models.ManyToManyField(to="address.address"),
        ),
        migrations.AddField(
            model_name="extendeduser",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="salon.salon",
            ),
        ),
        migrations.AlterField(
            model_name="extendeduser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
