# Generated by Django 4.1.4 on 2023-06-09 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0003_alter_salon_addresses"),
        ("user", "0004_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="salon",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="salon.salon"
            ),
            preserve_default=False,
        ),
    ]
