# Generated by Django 5.0.1 on 2024-03-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_customer_salon"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendeduser",
            name="full_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
