---
name: coding-standard
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dev dependencies
        run: pip install -r requirements_dev.txt

      - name: Set up pre-commit hooks
        run: pre-commit install

      - name: Pre‑commit (all hooks)
        run: pre-commit run --all-files
